### ISSUE TITLE
Error when running the tool on macos

### ISSUE THREAD

**Issue by FelixFrizzy** [JulianSampels/OntoMatch#18]
I tried to run the tool (in scope of OAEI 2024). I followed the instructions, but I get the error down below:

```
Traceback (most recent call last):
  File "/Users/localuser/.virtualenvs/ontomatch/lib/python3.12/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/localuser/.virtualenvs/ontomatch/lib/python3.12/site-packages/nltk/data.py", line 579, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords.zip/stopwords/

  Searched in:
    - '/Users/localuser/nltk_data'
    - '/Users/localuser/.virtualenvs/ontomatch/nltk_data'
    - '/Users/localuser/.virtualenvs/ontomatch/share/nltk_data'
    - '/Users/localuser/.virtualenvs/ontomatch/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/localuser/git/oaei/Matcher/OtherMatcher/OntoMatch/src/run_matcher.py", line 9, in <module>
    from batch_loaders.ontology_parsing import preprocessing
  File "/Users/localuser/git/oaei/Matcher/OtherMatcher/OntoMatch/src/batch_loaders/ontology_parsing/preprocessing.py", line 191, in <module>
    preprocessor = PreprocessingPipeline()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/localuser/git/oaei/Matcher/OtherMatcher/OntoMatch/src/batch_loaders/ontology_parsing/preprocessing.py", line 17, in __init__
    self.stop_words = set(stopwords.words('english')) 
                          ^^^^^^^^^^^^^^^
  File "/Users/localuser/.virtualenvs/ontomatch/lib/python3.12/site-packages/nltk/corpus/util.py", line 120, in __getattr__
    self.__load()
  File "/Users/localuser/.virtualenvs/ontomatch/lib/python3.12/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/Users/localuser/.virtualenvs/ontomatch/lib/python3.12/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/localuser/.virtualenvs/ontomatch/lib/python3.12/site-packages/nltk/data.py", line 579, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - '/Users/localuser/nltk_data'
    - '/Users/localuser/.virtualenvs/ontomatch/nltk_data'
    - '/Users/localuser/.virtualenvs/ontomatch/share/nltk_data'
    - '/Users/localuser/.virtualenvs/ontomatch/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
```

Steps to reproduce:
- MacOS Sonoma 14.3.1
- python 3.12.5
- `pip3 install -r requirements.txt`
- download and extract `val_avg_bleu=68.1000-step_count=5.ckpt` to `src/verbalizer/graph2text/outputs/t5-base_13881/`
- `cd src`
- `python3 run_matcher.py`
- get error message

**Comment by JulianSampels** [comment]
I'm currently unable to replicate this issue on a new Linux machine and am unsure why it persists on macOS. Does running the following script help resolve the problem? 
```
import nltk
nltk.download('stopwords')
```

**Comment by FelixFrizzy** [comment]
I included it in the run_matcher.py but it doesnt solve the issue. I will try to run it on debian and report back. Would be great if you open the issue again, maybe it can be fixed

**Comment by FelixFrizzy** [comment]
I solved the error on Mac (didnt try it on debian) with
`python3 -m nltk.downloader stopwords`

This should be included in the instructions as step
